/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace auth {
    export interface AuthService {
        login(
            data: LoginRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<LoginResponse>;
        refreshToken(
            data: RefreshTokenRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<RefreshTokenResponse>;
        register(
            data: RegisterRequest,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<RegisterResponse>;
    }
    export interface RegisterRequest {
        firstName?: string;
        lastName?: string;
        email?: string;
        phoneNumber?: string;
        password?: string;
        role?: string;
    }
    export interface RegisterResponse {
        firstName?: string;
        lastName?: string;
        email?: string;
        phoneNumber?: string;
    }
    export interface Credential {
        accessToken?: string;
        refreshToken?: string;
        accessTokenExpiresIn?: number;
        refreshTokenExpiresIn?: number;
    }
    export interface LoginRequest {
        email?: string;
        password?: string;
    }
    export interface LoginResponse {
        credential?: auth.Credential;
    }
    export interface RefreshTokenRequest {
        refreshToken?: string;
    }
    export interface RefreshTokenResponse {
        credential?: auth.Credential;
    }
}

